/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoundboxRouteImport } from './routes/soundbox'
import { Route as IndexRouteImport } from './routes/index'

const SoundboxRoute = SoundboxRouteImport.update({
  id: '/soundbox',
  path: '/soundbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/soundbox': typeof SoundboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/soundbox': typeof SoundboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/soundbox': typeof SoundboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/soundbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/soundbox'
  id: '__root__' | '/' | '/soundbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoundboxRoute: typeof SoundboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soundbox': {
      id: '/soundbox'
      path: '/soundbox'
      fullPath: '/soundbox'
      preLoaderRoute: typeof SoundboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoundboxRoute: SoundboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
